name: SAST Scanning
on:
  push:
    branches:
      - main
      - master  
  schedule:
      - cron:  '0 1 * * 6' 
  
permissions: 
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v2

      - name: Create temporary directory
        run: echo "WORKFLOWDIR=$(mktemp -d)" >> $GITHUB_ENV

      - name: Create environmental variables 
        run: |
          echo "SBOM_FILE=${WORKFLOWDIR}/spdx_sbom.json" >> $GITHUB_ENV
          echo "SBOM_ANALYSE_FILE=${WORKFLOWDIR}/results.json" >> $GITHUB_ENV
          echo "DEPENDABOT_FILE=${WORKFLOWDIR}/dependabot_alert.json" >> $GITHUB_ENV
          echo "ARTIFACT_PATH=${WORKFLOWDIR}/scan_result.json" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=SCA-${GITHUB_RUN_ID}-${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Run full scan
        run: |
          semgrep \
            --sarif --output report.sarif \
            --metrics=off \
            --config="p/default"

      - name: Upload Artifact
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 #v2
        with:
            name: report.sarif
            path: report.sarif
            
      - name: Download report
        uses: actions/download-artifact@v2
        with: 
          name: report.sarif

      
