name: SAST Scanning
on:
  #run the weekly scan on midnight Saturday
  schedule: 
      - cron:  '0 0 * * 6' 
  #run when changes happens to main/master branch
  push:
    branches:
      - main
      - master 

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v2

      - name: Create temporary directory
        run: echo "WORKFLOWDIR=$(mktemp -d)" >> $GITHUB_ENV

      - name: Create environmental variables 
        run: |
          echo "CODE_SCANNING_FILE=${WORKFLOWDIR}/github_scan_result.json" >> $GITHUB_ENV
          echo "ARTIFACT_PATH=${WORKFLOWDIR}/semgrep_scan_result.json" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=SAST-${GITHUB_RUN_ID}-${GITHUB_SHA}" >> $GITHUB_ENV
    
      - name: check if semgrep installed
        run: |
         if ! command -v semgrep &> /dev/null; then
           echo "semgrep is not installed, installing..."
           python3 -m pip install semgrep  
         else
           echo "semgrep is already installed"
         fi

      - name: Run full scan with Semgrep 
        run: |
          semgrep --json --output $ARTIFACT_PATH --metrics=off --config="p/default"
    
      - name: Get GitHub Code Scanning alert if enabled
        run: |
          # query the endpoint for repository level
          curl -L -o $CODE_SCANNING_FILE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "X-Accepted-GitHub-Permissions: pull_requests=read,contents=read; issues=read,contents=read" \
          https://api.github.com/repos/${{ github.repository }}/code-scanning/alerts

      - name: Upload Artifact
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 #v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            ${{ env.CODE_SCANNING_FILE }}
            ${{ env.ARTIFACT_PATH }}

      
