name: SCA Scanning
on:
  push:
    branches:
      - main
      - master  

permissions: 
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v2

      - name: Create temporary directory
        run: echo "WORKFLOWDIR=$(mktemp -d)" >> $GITHUB_ENV

      - name: Create environmental variables 
        run: |
          echo "SBOM_FILE=${WORKFLOWDIR}/spdx_sbom.json" >> $GITHUB_ENV
          echo "SBOM_ANALYSE_FILE=${WORKFLOWDIR}/results.json" >> $GITHUB_ENV
          echo "DEPENDABOT_FILE=${WORKFLOWDIR}/dependabot_alert.json" >> $GITHUB_ENV
          echo "ARTIFACT_PATH=${WORKFLOWDIR}/scan_result.json" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=SCA-${GITHUB_RUN_ID}-${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Get SPDX SBOM file from github dependency graph
        run: |
          # Dependency Graph SBOM
          curl -L -o $SBOM_FILE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/dependency-graph/sbom

          # parsing the fetched JSON data and transforming it into an SBOM format so trivy can process
          cat $SBOM_FILE  | jq '.sbom' > $SBOM_ANALYSE_FILE
          sed -i -e '${/^$/d;}' $SBOM_ANALYSE_FILE
    
      - name: running trivy for SCA on github SBOM file 
        run: |
          # check if trivy is installed, if not then installed 
          if ! command -v trivy &> /dev/null; then
            echo "trivy is not installed, installing..."
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin  
          else
            echo "trivy is already installed"
          fi

          #check if trivy is up-to-date

          #run trivy 
          trivy sbom $SBOM_ANALYSE_FILE --output $ARTIFACT_PATH

      - name: Get dependabot alert
        run: |
          curl -L -o $DEPENDABOT_FILE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "X-Accepted-GitHub-Permissions: pull_requests=read,contents=read; issues=read,contents=read" \
          https://api.github.com/repos/${{ github.repository }}/dependabot/alerts

      - name: Upload Artifact
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 #v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            ${{ env.ARTIFACT_PATH }}
            ${{ env.DEPENDABOT_FILE }}



      
